export const REPLACE_USER = 'REPLACE_USER';
export const RESET_APP_USER = 'RESET_APP_USER';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';