export const SET_REVERSE_GEOCODE = 'SET_REVERSE_GEOCODE';
export const GEOCODE_REQUEST_ERROR = 'GEOCODE_REQUEST_ERROR';

export const SAVE_POLYGON_COORDS = 'SAVE_POLYGON_COORDS';
export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT';
