
export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT';

export const FILTER_PROJECTS = 'FILTER_PROJECTS';
export const GET_PROJECTS_BY_TYPES = 'GET_PROJECTS_BY_TYPES';
export const GET_MAP_LAYERS = 'GET_MAP_LAYERS';
export const GET_MAP_WITH_SUBLAYERS = 'GET_MAP_WITH_SUBLAYERS';
export const GET_COMPONENTS_COUNTER  = 'GET_COMPONENTS_COUNTER';

export const SELECTED_LAYERS = 'SELECTED_LAYERS';
export const RESET_MAP = 'RESET_MAP';

export const GALLERY_PROBLEMS = 'GALLERY_PROBLEMS';
export const GALLERY_PROJECTS = 'GALLERY_PROJECTS';
export const SET_SELECTED_LAYERS = 'SET_SELECTED_LAYERS';

export const SET_FILTER_PROBLEM_OPTIONS = 'SET_FILTER_PROBLEM_OPTIONS';
export const SET_FILTER_PROJECT_OPTIONS = 'SET_FILTER_PROJECT_OPTIONS';
export const SET_FILTER_COORDINATES = 'SET_FILTER_COORDINATES';
export const GET_PARAM_FILTERS = 'GET_PARAM_FILTERS';
export const GET_COMPONENTS_BY_PROBLEMID = 'GET_COMPONENTS_BY_PROBLEMID';
export const SET_SPIN_FILTER = 'SET_SPIN_FILTER';
export const GET_HIGHLIGHTED = 'GET_HIGHLIGHTED';
export const SET_FILTER_COMPONENT_OPTIONS = 'SET_FILTER_COMPONENT_OPTIONS';
export const SET_FILTER_PROBLEMS = 'SET_FILTER_PROBLEMS';
export const SET_FILTER_PROJECTS = 'SET_FILTER_PROJECTS';
export const SET_FILTER_COMPONENTS = 'SET_FILTER_COMPONENTS';
export const SET_SPIN_CARD_PROBLEMS = 'SET_SPIN_CARD_PROBLEMS';
export const SET_SPIN_CARD_PROJECTS = 'SET_SPIN_CARD_PROJECTS';
export const SET_SPIN_MAP_LOADED = 'SET_SPIN_MAP_LOADED';
export const GET_FILTER_COMPONENTS_FOR_PROBLEMS = 'GET_FILTER_COMPONENTS_FOR_PROBLEMS';
export const FILTER_BY_COMPONENTS = 'FILTER_BY_COMPONENTS';
export const LOADER_TABLE_COMPONENTS = 'LOADER_TABLE_COMPONENTS';
export const SET_SELECTED_ON_MAP = 'SET_SELECTED_ON_MAP';
export const BBOX_COMPONENTS = 'BBOX_COMPONENTS';

export const MAP_SEARCH_QUERY = 'MAP_SEARCH_QUERY';
export const SET_APPLY_FILTERS = 'SET_APPLY_FILTERS';
export const ZOOM_PROJECT_OR_PROBLEMS = 'ZOOM_PROJECT_OR_PROBLEMS';
export const SET_TOOGLE_MODAL = 'SET_TOOGLE_MODAL';
export const SET_TAB_CARDS = 'SET_TAB_CARDS';
export const GET_PARAM_FILTER_PROJECTS = 'GET_PARAM_FILTER_PROJECTS';
export const GET_PARAM_FILTER_PROBLEMS = 'GET_PARAM_FILTER_PROBLEMS';
export const GET_PARAM_FILTER_COMPONENTS = 'GET_PARAM_FILTER_COMPONENTS';
export const SET_FILTER_TAB_NUMBER = 'SET_FILTER_TAB_NUMBER';
export const SET_BOUNDS_MAP = 'SET_BOUNDS_MAP';
export const GET_ZOOMAREA_FILTER = 'GET_ZOOMAREA_FILTER';
export const SET_OPACITY_LAYER = 'SET_OPACITY_LAYER';
export const SET_COORDINATES_JURISDICTION = 'SET_COORDINATES_JURISDICTION';
export const SET_NAME_ZOOMAREA = 'SET_NAME_ZOOMAREA';
export const SET_LABELS_FILTER_PROBLEMS = 'SET_LABELS_FILTER_PROBLEMS';
export const SET_LABELS_FILTER_PROJECTS = 'SET_LABELS_FILTER_PROJECTS';
export const SET_AUTOCOMPLETE = 'SET_AUTOCOMPLETE';


export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const FAVORITE_LIST = 'FAVORITE_LIST';
export const FAVORITE_CARDS_PROJECTS = 'FAVORITE_CARDS_PROJECTS';
export const FAVORITE_CARDS_PROBLEMS = 'FAVORITE_CARDS_PROBLEMS';

export const FAVORITE_CARDS_PROBLEMS_FILTERED = 'FAVORITE_CARDS_PROBLEMS_FILTERED';
export const FAVORITE_CARDS_PROJECTS_FILTERED = 'FAVORITE_CARDS_PROJECTS_FILTERED';


export const TUTORIAL_STATUS = 'TUTORIAL_STATUS';
export const CHANGE_CURRENT_POPUP = 'CHANGE_CURRENT_POPUP';

export const SET_COUNTER_TAB = 'SET_COUNTER_TAB';
export const FAVORITE_LOADER = 'FAVORITE_LOADER';

export const CREATE_SHOW_COMPONENTS = 'CREATE_SHOW_COMPONENTS';