export const SET_REVERSE_GEOCODE = 'SET_REVERSE_GEOCODE';
export const GEOCODE_REQUEST_ERROR = 'GEOCODE_REQUEST_ERROR';

export const SAVE_POLYGON_COORDS = 'SAVE_POLYGON_COORDS';
export const SAVE_MARKER_COORDS = 'SAVE_MARKER_COORDS';
export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT';

export const SET_REDIRECT = 'SET_REDIRECT';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const CLEAR_COORDINATES = 'CLEAR_COORDINATES';

export const FILTER_PROJECTS = 'FILTER_PROJECTS';
export const GET_MAP_LAYERS = 'GET_MAP_LAYERS';
