export const SET_SEARCH_WORD = 'SET_SEARCH_WORD';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const SET_FAVORITES = 'SET_FAVORITES';
export const PM_DELETE_FAVORITE = 'PM_DELETE_FAVORITE';
export const PM_ADD_FAVORITE = 'PM_ADD_FAVORITE';

