export const SET_SEARCH_WORD = 'SET_SEARCH_WORD';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const SET_FAVORITES = 'SET_FAVORITES';
export const PM_DELETE_FAVORITE = 'PM_DELETE_FAVORITE';
export const PM_ADD_FAVORITE = 'PM_ADD_FAVORITE';
export const SET_COLLAPSE_PHASE = 'SET_COLLAPSE_PHASE';
export const SCHEDULE_LIST = 'SCHEDULE_LIST';
export const PHASE_LIST = 'PHASE_LIST';
export const STATUS_COUNTER = 'STATUS_COUNTER';
export const UPDATE_PHASELIST = 'UPDATE_PHASELIST';
export const STATUS_LIST = 'STATUS_LIST';

