// TODO: eliminar
export const GET_USER_PROJECTS = 'GET_USER_PROJECT';
// TODO: eliminar
export const GET_USER_PROBLEMS = 'GET_USER_PROBLEMS';
// TODO: eliminar
export const SET_VALUE_LOADER_PROBLEM = 'SET_VALUE_LOADER_PROBLEM';
// TODO: eliminar
export const SET_VALUE_LOADER_PROJECT = 'SET_VALUE_LOADER_PROJECT';
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const COUNT_PROJECTS = 'COUNT_PROJECTS';
export const GET_PHOTO = 'GET_PHOTO';
export const SPIN = 'SPIN';
export const UPDATE_USER_INFORMATION = 'UPDATE_USER_INFORMATION';
export const RESET_PROFILE = 'RESET_PROFILE';
export const GET_GROUP_ORGANIZATION = 'GET_GROUP_ORGANIZATION';
// TODO: eliminar
export const GET_ALL_USER_PROJECTS = 'GET_ALL_USER_PROJECTS';
// TODO: eliminar
export const SET_VALUE_LOADER_ALL = 'SET_VALUE_LOADER_ALL';
export const GET_GUEST_USER = 'GET_GUEST_USER';