export const GET_USER_PROJECTS = 'GET_USER_PROJECT';
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const COUNT_PROJECTS = 'COUNT_PROJECTS';