export const GET_SPECIAL_ROW = 'GET_SPECIAL_ROW';
export const SET_REDIRECT = 'SET_REDIRECT';
export const SET_PROJECT_LOCATION = 'SET_PROJECT_LOCATION';
export const GET_LOCATION = 'GET_LOCATION';
export const SET_ACQUISITION_LOCATION = 'SET_ACQUISITION_LOCATION';