export const REQUEST_SHOW_MODAL_PROJECT = 'REQUEST_SHOW_MODAL_PROJECT';
export const REQUEST_COMPLETE_PROJECT_DATA = 'REQUEST_COMPLETE_PROJECT_DATA';
export const REQUEST_SET_LOCALITY = 'REQUEST_SET_LOCALITY';
export const REQUEST_SET_YEAR = 'REQUEST_SET_YEAR';
export const REQUEST_SET_TAB_KEY = 'REQUEST_SET_TAB_KEY';
export const REQUEST_SET_YEAR_LIST = 'REQUEST_SET_YEAR_LIST';
