// TODO: eliminar
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_ACTIVATED = 'DELETE_USER_ACTIVATED';
export const SAVE_USER_ACTIVATED = 'REPLACE_USER_ACTIVATED';
export const SAVE_USER_PENDING = 'REPLACE_USER_PENDING';
export const ADD_USER_ACTIVATED = 'ADD_USER_ACTIVATED';
export const ADD_USER_PENDING = 'ADD_USER_PENDING';
export const USER_ACTIVITY = 'USER_ACTIVITY';
export const ALL_USER_ACTIVITY = 'ALL_USER_ACTIVITY';
export const TIMES_LOGIN = 'TIMES_LOGIN';
