export const DATA_LIST_VIEW = [
  {
    key: 1,
    name: 'Sand Creek',
    phase: 'Preliminary',
    county: 'Arapahoe',
    cost: '$ 2,721,123',
    components: '23',
  },
  {
    key: 2,
    name: 'Littles Creek',
    phase: 'Initiation',
    county: 'Arapahoe',
    cost: '$ 1,320,141',
    components: '18',
  },
  {
    key: 3,
    name: 'Tollgate Creek ',
    phase: 'Final Design',
    county: 'Arapahoe',
    cost: '$ 1,515,003',
    components: '6',
  },
  {
    key: 4,
    name: 'Lee Gulch',
    phase: 'Preliminary',
    county: 'Arapahoe',
    cost: '$ 517,121',
    components: '23',
  },
  {
    key: 5,
    name: 'Willow Creek',
    phase: 'Initiation',
    county: 'Arapahoe',
    cost: '$ 1,341,211',
    components: '11',
  },
  {
    key: 6,
    name: 'Westminster MDP',
    phase: 'Final Design',
    county: 'Arapahoe',
    cost: '$ 350,000',
    components: '7',
  },
  {
    key: 7,
    name: 'Plum Creek',
    phase: 'Final Design',
    county: 'Arapahoe',
    cost: '$ 3,147,298',
    components: '14',
  },
  {
    key: 8,
    name: 'Sand Creek',
    phase: 'Preliminary',
    county: 'Arapahoe',
    cost: '$ 2,721,123',
    components: '23',
  },
  {
    key: 9,
    name: 'Sand Creek',
    phase: 'Preliminary',
    county: 'Arapahoe',
    cost: '$ 2,721,123',
    components: '23',
  },
  {
    key: 10,
    name: 'Sand Creek',
    phase: 'Preliminary',
    county: 'Arapahoe',
    cost: '$ 2,721,123',
    components: '23',
  },
  {
    key: 11,
    name: 'Sand Creek',
    phase: 'Preliminary',
    county: 'Arapahoe',
    cost: '$ 2,721,123',
    components: '23',
  },
  {
    key: 12,
    name: 'Sand Creek',
    phase: 'Preliminary',
    county: 'Arapahoe',
    cost: '$ 2,721,123',
    components: '23',
  },
];
export const DATA_USER_ACTIVITY = [
  {
    key: 1,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Admin Admin',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 2,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 3,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 4,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 5,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 6,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 7,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 8,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 9,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Admin Admin',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 10,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Admin Admin',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 11,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 12,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Admin Admin',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
];