export const DATA_USER_LIST = [
  {
    key: 1,
    name: ['Jon Villines','jon.vilines@mhfd.com', '/picture/user.png'],
    role: 'Super Admin',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 2,
    name: ['Jane Nelson','jane.nelson@mhfd.com', '/picture/user01.png'],
    role: 'MHFD Senior Manager',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 3,
    name: ['John Leone','John.Leone@mhfd.com', ''],
    role: 'Local Gov',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Inactive',
    actions: 'id',
  },
  {
    key: 4,
    name: ['Super Admin','super.admin@mhfd.com', ''],
    role: 'Super Admin',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 5,
    name: ['Super Admin','super.admin@mhfd.com', ''],
    role: 'Super Admin',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 6,
    name: ['MHFD SM','mhfd.sm@mhfd.com', ''],
    role: 'MHFD Senior Manager',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Inactive',
    actions: 'id',
  },
  {
    key: 7,
    name: ['Local Gov','local.gov@mhfd.com', ''],
    role: 'Local Gov',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 8,
    name: ['Super Admin','super.admin@mhfd.com', ''],
    role: 'Super Admin',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Inactive',
    actions: 'id',
  },
  {
    key: 9,
    name: ['MHFD SM','mhfd.sm@mhfd.com', ''],
    role: 'MHFD Senior Manager',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 10,
    name: ['Local Gov','local.gov@mhfd.com', ''],
    role: 'Local Gov',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 11,
    name: ['Super Admin','super.admin@mhfd.com', ''],
    role: 'Super Admin',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 12,
    name: ['MHFD SM','mhfd.sm@mhfd.com', ''],
    role: 'MHFD Senior Manager',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Inactive',
    actions: 'id',
  },
  {
    key: 13,
    name: ['Jon Villines','jon.vilines@mhfd.com', '/picture/user.png'],
    role: 'Super Admin',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 14,
    name: ['Jane Nelson','jane.nelson@mhfd.com', '/picture/user01.png'],
    role: 'MHFD Senior Manager',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 15,
    name: ['John Leone','John.Leone@mhfd.com', ''],
    role: 'Local Gov',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Inactive',
    actions: 'id',
  },
  {
    key: 16,
    name: ['Super Admin','super.admin@mhfd.com', ''],
    role: 'Super Admin',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 17,
    name: ['Super Admin','super.admin@mhfd.com', ''],
    role: 'Super Admin',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 18,
    name: ['MHFD SM','mhfd.sm@mhfd.com', ''],
    role: 'MHFD Senior Manager',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Inactive',
    actions: 'id',
  },
  {
    key: 19,
    name: ['Local Gov','local.gov@mhfd.com', ''],
    role: 'Local Gov',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 20,
    name: ['Super Admin','super.admin@mhfd.com', ''],
    role: 'Super Admin',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Inactive',
    actions: 'id',
  },
  {
    key: 21,
    name: ['MHFD SM','mhfd.sm@mhfd.com', ''],
    role: 'MHFD Senior Manager',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
  {
    key: 22,
    name: ['Local Gov','local.gov@mhfd.com', ''],
    role: 'Local Gov',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    city: 'Denver',
    status: 'Active',
    actions: 'id',
  },
];
export const DATA_USER_ACTIVITY = [
  {
    key: 1,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Admin Admin',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 2,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 3,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 4,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 5,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 6,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 7,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 8,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 9,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Admin Admin',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 10,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Admin Admin',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 11,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Jose Ramirez',
    city: '',
    status: 'Active',
    change: 'User Login',
  },
  {
    key: 12,
    dateTime: '05/23/2022 10:55 AM',
    user: 'Admin Admin',
    city: 'None',
    status: 'Active',
    change: 'User Login',
  },
];