export const DATA_SOLUTIONS = [
  {
    key: '1',
    component: ['Alpha St culvert',''],
    cost: ['$500,000',''],
    status: 'Active',
    type:'Increased Conveyance - Crossing'
  },
  {
    key: '2',
    component: ['Beta Ave culvert',''],
    cost: ['$1,200,000',''],
    status: 'Active',
    type:'Increased Conveyance - Crossing'
  },
  {
    key: '3',
    component: ['Channel imp - LDC @Alpha St',''],
    cost: ['$700,000',''],
    status: 'Active',
    type:'Increased Conveyance - Crossing'
  },
  {
    key: '4',
    component: ['Pedestrian bridge in park',''],
    cost: ['$250,000',''],
    status: 'Active',
    type:'Increased Conveyance - Stream'
  },
  {
    key: '5',
    component: ['Total Estimated Cost','total'],
    cost: ['$2,650,000',''],
  },
];

export const DATA_FINANCIALS = [
  {
    key: '1',
    agreement: ['18-08.12',''],
    amendment:'',
    partner: 'MHFD',
    phase: 'Funding',
    projected: ['$50,000', 'green'],
    encumbered: ['$50,000', 'green'],
    tyler: ['$50,000', 'green'],
    available: ['', 'purple'],
  },
  {
    key: '2',
    agreement: ['18-08.12',''],
    amendment:'',
    partner: 'SEMSWA',
    phase: 'Funding',
    projected: ['$50,000', 'green'],
    encumbered: ['$50,000', 'green'],
    tyler: ['$50,000', 'green'],
    available: ['$100,000', 'purple'],
  },
  {
    key: '3',
    agreement: ['18-08.12',''],
    amendment: 'A',
    partner: 'MHFD',
    phase: 'Concept',
    projected: ['$250,000', 'green'],
    encumbered:['$250,000', 'green'],
    tyler:['$250,000', 'green'],
    available: ['', 'purple'],
  },
  {
    key: '4',
    agreement: ['18-08.12',''],
    amendment: 'A',
    partner: 'SEMSWA',
    phase: 'Concept',
    projected: ['$250,000', 'green'],
    encumbered:['$250,000', 'green'],
    tyler:['$250,000', 'green'],
    available: ['', 'purple'],
  },
  {
    key: '5',
    agreement: ['20-06.11',''],
    amendment:'',
    partner: 'Wilson @ Co.',
    phase: 'Concept',
    projected: ['$12,100', 'red'],
    encumbered: ['$12,100', 'red'],
    tyler: ['$12,100', 'purple'],
    available: ['', 'purple'],
  },
  {
    key: '6',
    agreement: ['20-08.14',''],
    amendment:'',
    partner: 'ICON',
    phase: 'Concept',
    projected: ['$87,155', 'red'],
    encumbered: ['$87,155', 'red'],
    tyler: ['$87,155', 'purple'],
    available: ['$500,745', 'purple'],
  },
  {
    key: '7',
    agreement: ['18-08.12',''],
    amendment: 'B',
    partner: 'MHFD',
    phase: 'Preliminary',
    projected: ['$250,000', 'green'],
    encumbered:['$250,000', 'green'],
    tyler:['$250,000', 'green'],
    available: ['', 'purple'],
  },
  {
    key: '8',
    agreement: ['18-08.12',''],
    amendment: 'B',
    partner: 'SEMSWA',
    phase: 'Preliminary',
    projected: ['$250,000', 'green'],
    encumbered:['$250,000', 'green'],
    tyler:['$250,000', 'green'],
    available: ['', 'purple'],
  },
  {
    key: '9',
    agreement: ['20-06.11',''],
    amendment:'A',
    partner: 'Wilson @ Co.',
    phase: 'Preliminary',
    projected: ['$18,200', 'red'],
    encumbered: ['$18,200', 'red'],
    tyler: ['$18,200', 'purple'],
    available: ['', 'purple'],
  },
  {
    key: '10',
    agreement: ['21-11.02',''],
    amendment:'',
    partner: 'Wilson @ Co.',
    phase: 'Preliminary',
    projected: ['$15,600', 'red'],
    encumbered: ['$15,600', 'red'],
    tyler: ['$15,600', 'purple'],
    available: ['', 'purple'],
  },
  {
    key: '12',
    agreement: ['18-08.12',''],
    amendment: 'A',
    partner: 'MHFD',
    phase: 'Funding',
    projected: ['$50,000', 'green'],
    encumbered:['$50,000', 'green'],
    tyler:['$50,000', 'green'],
    available: ['$100,000', 'purple'],
  },
  {
    key: '13',
    agreement: ['18-08.12',''],
    amendment: 'A',
    partner: 'MHFD',
    phase: 'Funding',
    projected: ['$50,000', 'green'],
    encumbered:['$50,000', 'green'],
    tyler:['$50,000', 'green'],
    available: ['$100,000', 'purple'],
  },
  {
    key: '14',
    agreement: ['21-11.02',''],
    amendment:'',
    partner: 'Wilson @ Co.',
    phase: 'Preliminary',
    projected: ['$15,600', 'red'],
    encumbered: ['$15,600', 'red'],
    tyler: ['$15,600', 'purple'],
    available: ['', 'purple'],
  },
  {
    key: '15',
    agreement: ['20-18.14',''],
    amendment:'A',
    partner: 'ICON',
    phase: 'Preliminary',
    projected: ['$91,083', 'red'],
    encumbered: ['$91,083', 'red'],
    tyler: ['$91,083', 'red'],
    available: ['$500,745', 'purple'],
  },
  {
    key: '16',
    agreement: ['18-08.12',''],
    amendment: 'C',
    partner: 'MHFD',
    phase: 'Final',
    projected: ['$250,000', 'green'],
    encumbered:['$250,000', 'green'],
    tyler:['$250,000', 'green'],
    available: ['', 'purple'],
  },
  {
    key: '17',
    agreement: ['18-08.12',''],
    amendment: 'C',
    partner: 'SEMSWA',
    phase: 'Final',
    projected: ['$250,000', 'green'],
    encumbered:['$250,000', 'green'],
    tyler:['$250,000', 'green'],
    available: ['', 'purple'],
  },
  {
    key: '18',
    agreement: ['20-18.14',''],
    amendment:'B',
    partner: 'ICON',
    phase: 'Final',
    projected: ['$375,414', 'red'],
    encumbered: ['$375,414', 'red'],
    tyler: ['$375,414', 'red'],
    available: ['$1,000,448', 'purple'],
  },
  {
    key: '19',
    agreement: ['18-08.12',''],
    amendment:'D',
    partner: 'MHFD',
    phase: 'Construction',
    projected: ['$250,000', 'green'],
    encumbered: ['$0', 'green'],
    tyler: ['$0', 'green'],
    available: ['', 'purple'],
  },
  {
    key: '21',
    agreement: ['18-08.12',''],
    amendment: 'D',
    partner: 'SEMSWA',
    phase: 'Construction',
    projected: ['$250,000', 'green'],
    encumbered:['$0', 'green'],
    tyler:['$0', 'green'],
    available: ['', 'purple'],
  },
  {
    key: '22',
    agreement: ['18-08.12',''],
    amendment: 'D',
    partner: 'SSPRD',
    phase: 'Construction',
    projected: ['$350,000', 'green'],
    encumbered:['$0', 'green'],
    tyler:['$0', 'green'],
    available: ['', 'purple'],
  },
  {
    key: '23',
    agreement: ['',''],
    amendment: '',
    partner: 'Naranjo',
    phase: 'Constracting',
    projected: ['$750,000', 'red'],
    encumbered:['$0', 'purple'],
    tyler:['$0', 'purple'],
    available: ['', 'purple'],
  },
  {
    key: '24',
    agreement: ['',''],
    amendment:'',
    partner: 'Naranjo',
    phase: 'Construction',
    projected: ['$750,000', 'red'],
    encumbered:['$0', 'purple'],
    tyler:['$0', 'purple'],
    available: ['', 'purple'],
  },
  {
    key: '25',
    agreement: ['',''],
    amendment:'',
    partner: 'Western States',
    phase: 'Construction',
    projected: ['$250,000', 'red'],
    encumbered:['$0', 'purple'],
    tyler:['$0', 'purple'],
    available: ['$50,448', 'purple'],
  },
  {
    key: '26',
    agreement: ['',''],
    amendment: '',
    partner: 'Western States',
    phase: 'Establishment',
    projected: ['$200,000', 'red'],
    encumbered:['$0', 'purple'],
    tyler:['$0', 'purple'],
    available: ['', 'purple'],
  },
  {
    key: '27',
    agreement: ['',''],
    amendment: '',
    partner: 'ERO',
    phase: 'Establishment',
    projected: ['$50,000', 'red'],
    encumbered:['$0', 'purple'],
    tyler:['$0', 'purple'],
    available: ['-$199,552', 'purple'],
  },
  {
    key: '28',
    agreement: ['Total','total'],
    projected: ['$400,320', 'total'],
    encumbered:['$400,320', 'total'],
    tyler:['$400,320', 'total'],
    available: ['$50,000', 'total'],
  },
];
