export const dataTable = [
  {
    key: '1',
    phase: 'Initiation',
    mhfd: 'Jon Villines',
    status:'Not Started',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    cost: '420,000',
    stream:'Big Dry Creek',
    contact: 'ICON',
    view: 'id',
    options:'red',
  },
  {
    key: '2',
    phase: 'Preliminary',
    mhfd: 'Jon Villines',
    status:'Completed',
    serviceArea: 'Boulder',
    county: 'Jefferson',
    cost: '1,000,000',
    stream:'Big Dry Creek',
    contact: 'Dewberry',
    view: 'id',
    options:'red',
  },
  {
    key: '3',
    phase: 'Final Design',
    mhfd: 'Jon Villines',
    status:'Completed',
    serviceArea: 'North',
    county: 'Boulder',
    cost: '1,000,000',
    stream:'Big Dry Creek',
    contact: 'ICON',
    view: 'id',
    options:'red',
  },
  {
    key: '4',
    phase: 'Initiation',
    mhfd: 'Jon Villines',
    status:'Not Started',
    serviceArea: 'Sandy Creek',
    county: 'Douglas',
    cost: '679,000',
    stream:'Big Dry Creek',
    contact: 'RESPEC',
    view: 'id',
    options:'red',
  },
  {
    key: '5',
    phase: 'Preliminary',
    mhfd: 'Jon Villines',
    status:'Active',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    cost: '132,100',
    stream:'Big Dry Creek',
    contact: 'Dewberry',
    view: 'id',
    options:'red',
  },
  {
    key: '6',
    phase: 'Initiation',
    mhfd: 'Jon Villines',
    status:'Delayed',
    serviceArea: 'Northeast',
    county: 'Douglas',
    cost: '348,000',
    stream:'Big Dry Creek',
    contact: 'ICON',
    view: 'id',
    options:'red',
  },
  {
    key: '7',
    phase: 'Preliminary',
    mhfd: 'Jon Villines',
    status:'Not Started',
    serviceArea: 'Southwest',
    county: 'Denver',
    cost: '273,900',
    stream:'Big Dry Creek',
    contact: 'Calibre',
    view: 'id',
    options:'red',
  },
  {
    key: '8',
    phase: 'Initiation',
    mhfd: 'Jon Villines',
    status:'Delayed',
    serviceArea: 'Northeast',
    county: 'Douglas',
    cost: '348,000',
    stream:'Big Dry Creek',
    contact: 'ICON',
    view: 'id',
    options:'red',
  },
  {
    key: '9',
    phase: 'Preliminary',
    mhfd: 'Jon Villines',
    status:'Not Started',
    serviceArea: 'Southwest',
    county: 'Denver',
    cost: '273,900',
    stream:'Big Dry Creek',
    contact: 'Calibre',
    view: 'id',
    options:'red',
  },
];
export const dataTable01 = [
  {
    key: '1',
    phase: 'Final Design',
    mhfd: 'Jon Villines',
    status:'Completed',
    serviceArea: 'South',
    county: 'Arapahoe',
    cost: '3,450,000',
    stream:'Big Dry Creek',
    contact: 'Jacobs',
    view: 'id',
    options:'red',
  },
  {
    key: '2',
    phase: 'Preliminary',
    mhfd: 'Jon Villines',
    status:'Not Started',
    serviceArea: 'Sandy Creek',
    county: 'Douglas',
    cost: '124,700',
    stream:'Big Dry Creek',
    contact: 'Dewberry',
    view: 'id',
    options:'red',
  },
];
export const dataTable02 = [
  {
    key: '1',
    phase: 'Preliminary',
    mhfd: 'Jon Villines',
    status:'Not Started',
    serviceArea: 'Sandy Creek',
    county: 'Douglas',
    cost: '110.00 USD',
    stream:'Big Dry Creek',
    contact: 'Calibre',
    view: 'id',
    options:'red',
  },
  {
    key: '2',
    phase: 'Initiation',
    mhfd: 'Jon Villines',
    status:'Completed',
    serviceArea: 'Cherry Creek',
    county: 'Arapahoe',
    cost: '110.00 USD',
    stream:'Big Dry Creek',
    contact: 'ICON',
    view: 'id',
    options:'red',
  },
  {
    key: '3',
    phase: 'Final Design',
    mhfd: 'Jon Villines',
    status:'Delayed',
    serviceArea: 'Southwest',
    county: 'Douglas',
    cost: '110.00 USD',
    stream:'Big Dry Creek',
    contact: 'RESPEC',
    view: 'id',
    options:'red',
  },
];
export const dataTable00 = [
  {
    key: '1',
    phase: 'Preliminary',
    mhfd: 'Jon Villines',
    status:'Not Started',
    serviceArea: 'Sandy Creek',
    county: 'Douglas',
    cost: '110.00 USD',
    stream:'Big Dry Creek',
    contact: 'Calibre',
    view: 'id',
    options:'red',
  },
];