export const dataDot1 = [
  {
    name: 'I',
    id: 1,
    specificId: 1,
    jurisdiction: 'Centennial',
    data: [
      { phase: 'Draft', tasks: 6, status: 'Completed' }, //1
      { phase: 'WR', tasks: 8, status: 'Completed' }, //2
      { phase: 'WP', tasks: 12, status: 'Completed' }, //3
      { phase: 'Startup', tasks: 32, status: 'Completed' }, //4
      { phase: 'Funding', tasks: 6, status: 'Completed' }, //5
      { phase: 'ConsultantProcurement', tasks: 15, status: 'Active' }, //6
      { phase: 'ConceptualDesign', tasks: 10, status: 'Not Started' }, //7
      { phase: 'PreliminaryDesign', tasks: 9, status: 'Not Started' }, //8
      { phase: 'FinalDesign', tasks: 1, status: 'Not Started' }, //9
      { phase: 'ConstructionContracting', tasks: 2, status: 'Not Started' }, //10
      { phase: 'Construction', tasks: 6, status: 'Not Started' }, //11
      { phase: 'Documentation', tasks: 2, status: 'Not Started' }, //12
      { phase: 'Establishment', tasks: 6, status: 'Not Started' }, //13
      { phase: 'CloseOut', tasks: 2, status: 'Not Started' }, //14
      { phase: 'Closed', tasks: 2, status: 'Not Started' }, //15
    ],
  },
  {
    name: 'K',
    id: 1,
    specificId: 2,
    jurisdiction: 'Centennial',
    data: [
      { phase: 'Draft', tasks: 12, status: 'Completed' },
      { phase: 'WR', tasks: 12, status: 'Completed' },
      { phase: 'WP', tasks: 8, status: 'Completed' },
      { phase: 'Startup', tasks: 2, status: 'Completed' },
      { phase: 'Funding', tasks: 3, status: 'Completed' },
      { phase: 'Consultant', tasks: 5, status: 'Active' },
      { phase: 'ConceptualDesign', tasks: 16, status: 'Active' },
      { phase: 'PreliminaryDesign', tasks: 11, status: 'Not Started' },
      { phase: 'FinalDesign', tasks: 3, status: 'Not Started' },
      { phase: 'ConstructionContracting', tasks: 14, status: 'Not Started' },
      { phase: 'Construction', tasks: 11, status: 'Not Started' },
      { phase: 'Documentation', tasks: 2, status: 'Not Started' },
      { phase: 'Establishment', tasks: 6, status: 'Not Started' },
      { phase: 'CloseOut', tasks: 2, status: 'Not Started' },
      { phase: 'Closed', tasks: 2, status: 'Not Started' },
    ],
  },
  {
    name: 'C',
    id: 1,
    specificId: 3,
    jurisdiction: 'Centennial',
    data: [
      { phase: 'Draft', tasks: 3, status: 'Completed' },
      { phase: 'WR', tasks: 11, status: 'Completed' },
      { phase: 'WP', tasks: 2, status: 'Completed' },
      { phase: 'Startup', tasks: 10, status: 'Completed' },
      { phase: 'Funding', tasks: 4, status: 'Completed' },
      { phase: 'Consultant', tasks: 7, status: 'Active' },
      { phase: 'ConceptualDesign', tasks: 6, status: 'Active' },
      { phase: 'PreliminaryDesign', tasks: 3, status: 'Not Started' },
      { phase: 'FinalDesign', tasks: 4, status: 'Not Started' },
      { phase: 'ConstructionContracting', tasks: 17, status: 'Not Started' },
      { phase: 'Construction', tasks: 4, status: 'Not Started' },
      { phase: 'Documentation', tasks: 2, status: 'Not Started' },
      { phase: 'Establishment', tasks: 6, status: 'Not Started' },
      { phase: 'CloseOut', tasks: 2, status: 'Not Started' },
      { phase: 'Closed', tasks: 2, status: 'Not Started' },
    ],
  },
  {
    name: 'S',
    id: 1,
    specificId: 4,
    jurisdiction: 'Centennial',
    data: [
      { phase: 'Draft', tasks: 5, status: 'Completed' },
      { phase: 'WR', tasks: 9, status: 'Completed' },
      { phase: 'WP', tasks: 12, status: 'Completed' },
      { phase: 'Startup', tasks: 8, status: 'Completed' },
      { phase: 'Funding', tasks: 10, status: 'Active' },
      { phase: 'Consultant', tasks: 12, status: 'Not Started' },
      { phase: 'ConceptualDesign', tasks: 23, status: 'Not Started' },
      { phase: 'PreliminaryDesign', tasks: 2, status: 'Not Started' },
      { phase: 'FinalDesign', tasks: 5, status: 'Not Started' },
      { phase: 'ConstructionContracting', tasks: 5, status: 'Not Started' },
      { phase: 'Construction', tasks: 9, status: 'Not Started' },
      { phase: 'Documentation', tasks: 2, status: 'Not Started' },
      { phase: 'Establishment', tasks: 6, status: 'Not Started' },
      { phase: 'CloseOut', tasks: 2, status: 'Not Started' },
      { phase: 'Closed', tasks: 2, status: 'Not Started' },
    ],
  },
  {
    name: 'L',
    id: 1,
    specificId: 5,
    jurisdiction: 'Centennial',
    data: [
      { phase: 'Draft', tasks: 6, status: 'Completed' },
      { phase: 'WR', tasks: 8, status: 'Completed' },
      { phase: 'WP', tasks: 11, status: 'Completed' },
      { phase: 'Startup', tasks: 4, status: 'Completed' },
      { phase: 'Funding', tasks: 12, status: 'Active' },
      { phase: 'Consultant', tasks: 13, status: 'Not Started' },
      { phase: 'ConceptualDesign', tasks: 13, status: 'Not Started' },
      { phase: 'PreliminaryDesign', tasks: 2, status: 'Not Started' },
      { phase: 'FinalDesign', tasks: 6, status: 'Not Started' },
      { phase: 'ConstructionContracting', tasks: 2, status: 'Not Started' },
      { phase: 'Construction', tasks: 10, status: 'Not Started' },
      { phase: 'Documentation', tasks: 2, status: 'Not Started' },
      { phase: 'Establishment', tasks: 6, status: 'Not Started' },
      { phase: 'CloseOut', tasks: 2, status: 'Not Started' },
      { phase: 'Closed', tasks: 2, status: 'Not Started' },
    ],
  },
  {
    name: 'M',
    id: 1,
    specificId: 6,
    jurisdiction: 'Centennial',
    data: [
      { phase: 'Draft', tasks: 2, status: 'Completed' },
      { phase: 'WR', tasks: 1, status: 'Completed' },
      { phase: 'WP', tasks: 5, status: 'Completed' },
      { phase: 'Startup', tasks: 7, status: 'Completed' },
      { phase: 'Funding', tasks: 34, status: 'Active' },
      { phase: 'Consultant', tasks: 8, status: 'Not Started' },
      { phase: 'ConceptualDesign', tasks: 10, status: 'Not Started' },
      { phase: 'PreliminaryDesign', tasks: 6, status: 'Not Started' },
      { phase: 'FinalDesign', tasks: 4, status: 'Not Started' },
      { phase: 'ConstructionContracting', tasks: 7, status: 'Not Started' },
      { phase: 'Construction', tasks: 8, status: 'Not Started' },
      { phase: 'Documentation', tasks: 2, status: 'Not Started' },
      { phase: 'Establishment', tasks: 6, status: 'Not Started' },
      { phase: 'CloseOut', tasks: 2, status: 'Not Started' },
      { phase: 'Closed', tasks: 2, status: 'Not Started' },
    ],
  },
  {
    name: 'G',
    id: 1,
    specificId: 7,
    jurisdiction: 'Centennial',
    data: [
      { phase: 'Draft', tasks: 1, status: 'Completed' },
      { phase: 'WR', tasks: 8, status: 'Completed' },
      { phase: 'WP', tasks: 3, status: 'Completed' },
      { phase: 'Startup', tasks: 1, status: 'Completed' },
      { phase: 'Funding', tasks: 65, status: 'Active' },
      { phase: 'Consultant', tasks: 32, status: 'Not Started' },
      { phase: 'ConceptualDesign', tasks: 12, status: 'Not Started' },
      { phase: 'PreliminaryDesign', tasks: 16, status: 'Not Started' },
      { phase: 'FinalDesign', tasks: 10, status: 'Not Started' },
      { phase: 'ConstructionContracting', tasks: 10, status: 'Not Started' },
      { phase: 'Construction', tasks: 3, status: 'Not Started' },
      { phase: 'Documentation', tasks: 2, status: 'Not Started' },
      { phase: 'Establishment', tasks: 6, status: 'Not Started' },
      { phase: 'CloseOut', tasks: 2, status: 'Not Started' },
      { phase: 'Closed', tasks: 2, status: 'Not Started' },
    ],
  },
  //{name: 'V', id: 1,specificId:1, jurisdiction:'Centennial', data: [{phase:'Draft' ,tasks: 33, status: 'Completed'}, {phase:'WR' ,tasks: 3, status: 'Completed'}, {phase:'WP' ,tasks: 12, status: 'Completed'}, {phase:'Startup' ,tasks: 11, status: 'Completed'}, {phase:'Funding' ,tasks: 23, status: 'Completed'}, {phase:'Consultant' ,tasks: 12, status: 'Active'}, {phase:'ConceptualDesign' ,tasks: 2, status: 'Not Started'}, {phase:'PreliminaryDesign' ,tasks: 13, status: 'Not Started'}, {phase:'FinalDesign' ,tasks: 12, status: 'Not Started'}, {phase:'ConstructionContracting' ,tasks: 9, status: 'Not Started'}, {phase:'Construction' ,tasks: 22, status: 'Not Started'}, {phase:'Documentation' ,tasks: 2, status: 'Not Started'}, {phase:'Establishment' ,tasks: 6, status: 'Not Started'}, {phase:'CloseOut' ,tasks: 10, status: 'Not Started'}, {phase:'Closed' ,tasks: 3, status: 'Not Started'}]},
  //{name: 'X', id: 1,specificId:1, jurisdiction:'Centennial', data: [{phase:'Draft' ,tasks: 11, status: 'Completed'}, {phase:'WR' ,tasks: 8, status: 'Completed'}, {phase:'WP' ,tasks: 4, status: 'Completed'}, {phase:'Startup' ,tasks: 32, status: 'Completed'}, {phase:'Funding' ,tasks: 15, status: 'Active'}, {phase:'Consultant' ,tasks: 8, status: 'Not Started'}, {phase'ConceptualDesign': ,tasks: 10, status: 'Not Started'}, {phase:'PreliminaryDesign' ,tasks: 11, status: 'Not Started'}, {phase:'FinalDesign' ,tasks: 1, status: 'Not Started'}, {phase:'ConstructionContracting' ,tasks: 13, status: 'Not Started'}, {phase:'Construction' ,tasks: 8, status: 'Not Started'}, {phase:'Documentation' ,tasks: 2, status: 'Not Started'}, {phase:'Establishment' ,tasks: 6, status: 'Not Started'}, {phase:'CloseOut' ,tasks: 10, status: 'Not Started'}, {phase:'Closed' ,tasks: 3, status: 'Not Started'}]},
  //{name: 'A', id: 1,specificId:1, jurisdiction:'Centennial', data: [{phase:'Draft' ,tasks: 8, status: 'Completed'}, {phase:'WR' ,tasks: 10, status: 'Completed'}, {phase:'WP' ,tasks: 10, status: 'Completed'}, {phase:'Startup' ,tasks: 12, status: 'Completed'}, {phase:'Funding' ,tasks: 1, status: 'Active'}, {phase:'Consultant' ,tasks: 2, status: 'Delayed'}, {phase:'ConceptualDesign' ,tasks: 12, status: 'Not Started'}, {phase:'PreliminaryDesign' ,tasks: 10, status: 'Not Started'}, {phase:'FinalDesign' ,tasks: 2, status: 'Not Started'}, {phase:'ConstructionContracting' ,tasks: 21, status: 'Not Started'}, {phase:'Construction' ,tasks: 7, status: 'Not Started'}, {phase:'Documentation' ,tasks: 2, status: 'Not Started'}, {phase:'Establishment' ,tasks: 6, status: 'Not Started'}, {phase:'CloseOut' ,tasks: 10, status: 'Not Started'}, {phase:'Closed' ,tasks: 3, status: 'Not Started'}]},
  //{name: 'R', id: 1,specificId:1, jurisdiction:'Centennial', data: [{phase:'Draft' ,tasks: 23, status: 'Completed'}, {phase:'WR' ,tasks: 4, status: 'Completed'}, {phase:'WP' ,tasks: 10, status: 'Completed'}, {phase:'Startup' ,tasks: 21, status: 'Completed'}, {phase:'Funding' ,tasks: 2, status: 'Delayed'}, {phase:'Consultant' ,tasks: 5, status: 'Delayed'}, {phase:'ConceptualDesign' ,tasks: 9, status: 'Not Started'}, {phase:'PreliminaryDesign' ,tasks: 9, status: 'Not Started'}, {phase:'FinalDesign' ,tasks: 11, status: 'Not Started'}, {phase:'ConstructionContracting' ,tasks: 2, status: 'Not Started'}, {phase:'Construction' ,tasks: 44, status: 'Not Started'}, {phase:'Documentation' ,tasks: 2, status: 'Not Started'}, {phase:'Establishment' ,tasks: 6, status: 'Not Started'}, {phase:'CloseOut' ,tasks: 10, status: 'Not Started'}, {phase:'Closed' ,tasks: 3, status: 'Not Started'}]}
];

export const dataDot2 = [
  {
    name: 'V',
    id: 2,
    specificId: 1,
    jurisdiction: 'CommerceCity',
    data: [
      { phase: 'Draft', tasks: 33, status: 'Completed' },
      { phase: 'WR', tasks: 3, status: 'Completed' },
      { phase: 'WP', tasks: 12, status: 'Completed' },
      { phase: 'Startup', tasks: 11, status: 'Completed' },
      { phase: 'Funding', tasks: 23, status: 'Completed' },
      { phase: 'Consultant', tasks: 12, status: 'Active' },
      { phase: 'ConceptualDesign', tasks: 2, status: 'Not Started' },
      { phase: 'PreliminaryDesign', tasks: 13, status: 'Not Started' },
      { phase: 'FinalDesign', tasks: 12, status: 'Not Started' },
      { phase: 'ConstructionContracting', tasks: 9, status: 'Not Started' },
      { phase: 'Construction', tasks: 22, status: 'Not Started' },
      { phase: 'Documentation', tasks: 2, status: 'Not Started' },
      { phase: 'Establishment', tasks: 6, status: 'Not Started' },
      { phase: 'CloseOut', tasks: 9, status: 'Not Started' },
      { phase: 'Closed', tasks: 22, status: 'Not Started' },
    ],
  },
  {
    name: 'X',
    id: 2,
    specificId: 2,
    jurisdiction: 'CommerceCity',
    data: [
      { phase: 'Draft', tasks: 11, status: 'Completed' },
      { phase: 'WR', tasks: 8, status: 'Completed' },
      { phase: 'WP', tasks: 4, status: 'Completed' },
      { phase: 'Startup', tasks: 32, status: 'Completed' },
      { phase: 'Funding', tasks: 15, status: 'Active' },
      { phase: 'Consultant', tasks: 8, status: 'Not Started' },
      { phase: 'ConceptualDesign', tasks: 10, status: 'Not Started' },
      { phase: 'PreliminaryDesign', tasks: 11, status: 'Not Started' },
      { phase: 'FinalDesign', tasks: 1, status: 'Not Started' },
      { phase: 'ConstructionContracting', tasks: 13, status: 'Not Started' },
      { phase: 'Construction', tasks: 8, status: 'Not Started' },
      { phase: 'Documentation', tasks: 2, status: 'Not Started' },
      { phase: 'Establishment', tasks: 6, status: 'Not Started' },
      { phase: 'CloseOut', tasks: 9, status: 'Not Started' },
      { phase: 'Closed', tasks: 22, status: 'Not Started' },
    ],
  },
];

export const dataDot3 = [
  {
    name: 'A',
    id: 3,
    specificId: 1,
    jurisdiction: 'Denver',
    data: [
      { phase: 'Draft', tasks: 8, status: 'Completed' },
      { phase: 'WR', tasks: 10, status: 'Completed' },
      { phase: 'WP', tasks: 10, status: 'Completed' },
      { phase: 'Startup', tasks: 12, status: 'Completed' },
      { phase: 'Funding', tasks: 1, status: 'Active' },
      { phase: 'Consultant', tasks: 2, status: 'Delayed' },
      { phase: 'ConceptualDesign', tasks: 12, status: 'Not Started' },
      { phase: 'PreliminaryDesign', tasks: 10, status: 'Not Started' },
      { phase: 'FinalDesign', tasks: 2, status: 'Not Started' },
      { phase: 'ConstructionContracting', tasks: 21, status: 'Not Started' },
      { phase: 'Construction', tasks: 7, status: 'Not Started' },
      { phase: 'Documentation', tasks: 2, status: 'Not Started' },
      { phase: 'Establishment', tasks: 6, status: 'Not Started' },
      { phase: 'CloseOut', tasks: 9, status: 'Not Started' },
      { phase: 'Closed', tasks: 22, status: 'Not Started' },
    ],
  },
  {
    name: 'R',
    id: 3,
    specificId: 2,
    jurisdiction: 'Denver',
    data: [
      { phase: 'Draft', tasks: 23, status: 'Completed' },
      { phase: 'WR', tasks: 4, status: 'Completed' },
      { phase: 'WP', tasks: 10, status: 'Completed' },
      { phase: 'Startup', tasks: 21, status: 'Completed' },
      { phase: 'Funding', tasks: 2, status: 'Delayed' },
      { phase: 'Consultant', tasks: 5, status: 'Delayed' },
      { phase: 'ConceptualDesign', tasks: 9, status: 'Not Started' },
      { phase: 'PreliminaryDesign', tasks: 9, status: 'Not Started' },
      { phase: 'FinalDesign', tasks: 11, status: 'Not Started' },
      { phase: 'ConstructionContracting', tasks: 2, status: 'Not Started' },
      { phase: 'Construction', tasks: 44, status: 'Not Started' },
      { phase: 'Documentation', tasks: 2, status: 'Not Started' },
      { phase: 'Establishment', tasks: 6, status: 'Not Started' },
      { phase: 'CloseOut', tasks: 9, status: 'Not Started' },
      { phase: 'Closed', tasks: 22, status: 'Not Started' },
    ],
  },
  {
    name: 'V',
    id: 3,
    specificId: 3,
    jurisdiction: 'Denver',
    data: [
      { phase: 'Draft', tasks: 33, status: 'Completed' },
      { phase: 'WR', tasks: 3, status: 'Completed' },
      { phase: 'WP', tasks: 12, status: 'Completed' },
      { phase: 'Startup', tasks: 11, status: 'Completed' },
      { phase: 'Funding', tasks: 23, status: 'Completed' },
      { phase: 'Consultant', tasks: 12, status: 'Active' },
      { phase: 'ConceptualDesign', tasks: 2, status: 'Not Started' },
      { phase: 'PreliminaryDesign', tasks: 13, status: 'Not Started' },
      { phase: 'FinalDesign', tasks: 12, status: 'Not Started' },
      { phase: 'ConstructionContracting', tasks: 9, status: 'Not Started' },
      { phase: 'Construction', tasks: 22, status: 'Not Started' },
      { phase: 'Documentation', tasks: 2, status: 'Not Started' },
      { phase: 'Establishment', tasks: 6, status: 'Not Started' },
      { phase: 'CloseOut', tasks: 9, status: 'Not Started' },
      { phase: 'Closed', tasks: 22, status: 'Not Started' },
    ],
  },
];

export const colorScale: any = {
  completed: '#5E5FE2',
  active: '#047CD7',
  notStarted: '#D4D2D9',
  delayed: '#F5575C',
};
